<ul class="menu_dropdown" id="menu_boutiques" style="top: 30px;">
	<span id="puce_dropdown_parcourir" class="glyphicon glyphicon-triangle-top puce_dropdown"></span>

	<li class="item first">
		<a href="#">
			Téléchargement de musique 
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<h6 class="menu-caption">Toute votre musique. Partout.</h6>
		<ul class="submenu col-xs-12" style="width: 260px;">
			<li class="subitem title">
				<span class="subitem-title">Téléchargement de musique.</span>
				<h6 class="menu-caption">Toute votre musique. Partout.</h6>
			</li>
			<li class="subitem">
				<a href="#">Téléchargement de musique</a>
				<h6 class="menu-caption">Plus de 30 millions de titres à télécharger</h6>
			</li>
			<li class="subitem"><a href="#">Meilleures ventes</a></li>
			<li class="subitem"><a href="#">Nouveautés</a></li>
			<li class="subitem"><a href="#">Promotions</a></li>
			<hr>
			<li class="subitem">
				<a href="#">Votre bibliothèque Amazon Music</a> 
				<h6 class="menu-caption">Toute votre musique. Partout.</h6>
			</li>
			<li class="subitem">
				<a href="#">Applications Amazon Music</a> 
				<h6 class="menu-caption">Votre musique sur tous vos appareils</h6>
			</li>
		</ul>
	</li>
	
	<li class="item">
		<a href="#">
			Amazon Cloud Drive
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<h6 class="menu-caption">5 Go d'espace de stockage gratuit.</h6>
		<ul class="submenu col-xs-12" style="width:499px;">
			<li class="subitem title">
				<span class="subitem-title">Amazon Cloud Drive</span>
				<h6 class="menu-caption">Toute votre musique. Partout.</h6>
			</li>
			<li class="subitem">
				<a href="#">A propos de Cloud Drive</a>
				<h6 class="menu-caption">Stockage sécurisé de vos photos et autres fichiers</h6>
			</li>
			<li class="subitem">
				<a href="#">Téléchargez les applications gratuites</a>
				<h6 class="menu-caption">Pour PC, iOS, Android</h6>
			</li>
			<li class="subitem">
				<a href="#">Stockage illimité de photos</a>
				<h6 class="menu-caption">Gratuit avec Amazon Premium</h6>
			</li>
			<li class="subitem">
				<a href="#">Plans et Prix</a>
				<h6 class="menu-caption">Commencez avec 5 Go gratuits</h6>
			</li>
			<li class="subitem">
				<a href="#">Identifiez-vous</a> 
				<h6 class="menu-caption">Affichez et gérez votre contenu numérique</h6>
			</li>
			
			<li>
				<img class="img_promo" src="<?php echo $this->baseUrl() . '/imgs/img_promo/amazonCloud.png' ?>" alt="Amazon Cloud">
			</li>
		</ul>
	</li>
	
	
	<li class="item">
		<a href="#">
			Liseuses Kindle & ebooks
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Liseuses Kindle</span>
				</li>
				<li class="subitem">
					<a href="#">Kindle</a>
					<h6 class="menu-caption">Petit, léger, abordable et avec écran tactile</h6>
				</li>
				<li class="subitem">
					<a href="#">Kindle Paperwhite</a>
					<h6 class="menu-caption"> Notre liseuse phare, encore améliorée</h6>
				</li>
				<li class="subitem">
					<a href="#">Kindle Voyage</a>
					<h6 class="menu-caption">Conçu avec passion pour nos lecteurs</h6>
				</li>
				<li class="subitem">
					<a href="#">Pack Kindle pour les enfants</a>
					<h6 class="menu-caption">Plus qu'un écran, un livre</h6>
				</li>
				<li class="subitem">
					<a href="#">Accessoires</a>
					<h6 class="menu-caption">Étuis, chargeurs, housses et plus encore</h6>
				</li>
				
				<hr>
				
				<li class="subitem title">
					<span class="subitem-title">Boutique Kindle</span>
				</li>
				<li class="subitem"><a href="#">Tous les ebooks Kindle</a></li>
				<li class="subitem">
					<a href="#">Kindle Unlimited</a> 
					<h6 class="menu-caption">Lisez en toute liberté</h6>
				</li>
				<li class="subitem"><a href="#">Offres Éclair Kindle</a></li>
				
			</div>
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Applications et ressources</span>
				</li>
				<li class="subitem">
					<a href="#">Applications de lecture gratuites</a>
					<h6 class="menu-caption">Pour PC, iPad, iPhone, Android, et plus</h6>
					<h6 class="menu-caption">encore</h6>
				</li>
				<li class="subitem">
					<a href="#">Kindle Cloud Reader</a> 
					<h6 class="menu-caption">Lisez vos livres Kindle dans un navigateur</h6>
				</li>
				<li class="subitem"><a href="#">Gérer votre contenu et vos appareils</a></li>
				
			</div>
				
			<li>
				<img class="img_promo" style="
				bottom: -44px;
				right: -30px;
				width: 540px;
				height: 523px;" src="<?php echo $this->baseUrl() . '/imgs/img_promo/kindle.png' ?>" alt="Kindle">
			</li>
		</ul>
	</li>
	

	<li class="item">
		<a href="#">
			Tablettes Fire 
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Tablettes Fire</span>
				</li>
				<li class="subitem">
					<a href="#">Fire - Nouveau</a>
					<h6 class="menu-caption">Prix incroyable. Haute performance</h6>
				</li>
				<li class="subitem">
					<a href="#">Fire HD 6</a>
					<h6 class="menu-caption">Tablette puissante au format poche</h6>
				</li>
				<li class="subitem">
					<a href="#">Fire HDX 8.9</a>
					<h6 class="menu-caption">Notre tablette la plus puissante, qui sait tout </h6>
					<h6 class="menu-caption">faire</h6>
				</li>
				<li class="subitem">
					<a href="#">Accessoires</a>
					<h6 class="menu-caption">Étuis, chargeurs, stylets et plus encore</h6>
				</li>
			</div>
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Applications et ressources</span>
				</li>
				<li class="subitem">
					<a href="#">Applis</a>
				</li>
				<li class="subitem">
					<a href="#">Jeux</a> 
				</li>
				<li class="subitem">
					<a href="#">MP3</a>
				</li>
				<li class="subitem">
					<a href="#">Tous les ebooks Kindle</a>
				</li>
				<li class="subitem">
					<a href="#">Gérer votre contenu et vos appareils</a>
				</li>
			</div>
			
			<li>
				<img class="img_promo" src="<?php echo $this->baseUrl() . '/imgs/img_promo/tablettesFire.png' ?>" alt="Tablettes Fire">
			</li>
		</ul>
	</li>

	
	<li class="item">
		<a href="#">
			App-Shop pour Android
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">App-Shop pour Android</span>
				</li>
				<li class="subitem">
					<a href="#">Underground Applis et Jeux</a>
					<h6 class="menu-caption">Applis vraiment gratuites sur Amazon</h6>
				</li>
				<li class="subitem">
					<a href="#">Tous les applis et jeux</a>
				</li>
				<li class="subitem">
					<a href="#">Jeux</a>
				</li>
				<li class="subitem">
					<a href="#">Amazon Coins</a>
					<h6 class="menu-caption">Dépensez moins, jouez plus</h6>
				</li>
				<li class="subitem">
					<a href="#">Applications Amazon</a>
					<h6 class="menu-caption">Amazon Mobile, Kindle, MP3 et plus encore</h6>
				</li>
				<li class="subitem">
					<a href="#">Vos applis et vos appareils</a>
					<h6 class="menu-caption"> Voir mes applis et gérer mes appareils</h6>
				</li>
			</div>
			<div class="col-xs-6">
			</div>
			
			<li>
				<img class="img_promo" style="
					bottom: -24px;
					right: -20px;
					width: 480px;
					height: 472px; 
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/appShop.png' ?>" alt="Applications">
			</li>

		</ul>
	</li>		
	
	
	
	<li class="item">
		<a href="#">
			Jeux et Logiciels Digitaux
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<h6 class="menu-caption">En téléchargement.</h6>
		<ul class="submenu col-xs-12" style="width:238px;">
			<li class="subitem title">
				<span class="subitem-title">Jeux et Logiciels Digitaux</span>
				<h6 class="menu-caption">En téléchargement</h6>
			</li>
			<li class="subitem">
				<a href="#">Jeux vidéo à télécharger</a>
				<h6 class="menu-caption">Pour Consoles, PC et Mac</h6>
			</li>
			<li class="subitem">
				<a href="#">Jeux Free-to-Play</a>
				<h6 class="menu-caption">Pour Consoles, PC et Mac</h6>
			</li>
			<li class="subitem">
				<a href="#">Logiciels à télécharger</a>
				<h6 class="menu-caption">Pour Consoles, PC et Mac</h6>
			</li>
			<li class="subitem">
				<a href="#">Votre bibliothèque de jeux et logiciels</a>
			</li>
		</ul>
	</li>
	
	<hr>
	
	
	
	<li class="item">
		<a href="#">
			Livres
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Livres</span>
				</li>
				<li class="subitem">
					<a href="#">Tous les livres</a>
				</li>
				<li class="subitem">
					<a href="#">Tous les ebooks Kindle</a>
				</li>
				<li class="subitem">
					<a href="#">Livres anglais et étrangers</a>
				</li>
				<li class="subitem">
					<a href="#">Manuels scolaires et parascolaires</a>
				</li>
				<li class="subitem">
					<a href="#">Livres audio</a>
				</li>
			</div>
			<div class="col-xs-6">
			</div>
			<li>
				<img class="img_promo" style="
					bottom: -35px;
					right: -22px;
					width: 511px;
					height: 431px;
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/livres.png' ?>" alt="Livres">
			</li>
		</ul>
	</li>

	<li class="item">
		<a href="#">
			Musique, DVD et Blu-ray
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Musique, DVD et Blu-ray</span>
				</li>
				<li class="subitem">
					<a href="#">CD & Vinyles</a>
				</li>
				<li class="subitem">
					<a href="#">Musique classique</a>
				</li>
				<li class="subitem">
					<a href="#">Téléchargement de musique</a>
				</li>
				<li class="subitem">
					<a href="#">Instruments de musique & Sono</a>
				</li>
				<li class="subitem">
					<a href="#">DVD & Blu-ray</a>
				</li>
				<li class="subitem">
					<a href="#">Séries TV</a>
				</li>
				<li class="subitem">
					<a href="#">Blu-ray</a>
				</li>
			</div>
			<div class="col-xs-6">
			</div>
			
			<li>
				<img class="img_promo" style="
					bottom: -36px;
					right: -22px;
					width: 499px;
					height: 469px;
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/DVD.png' ?>" alt="DVD">
			</li>
		</ul>
	</li>
	
	<li class="item">
		<a href="#">
			Jeux vidéos et Consoles
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Jeux vidéo et Consoles</span>
				</li>
				<li class="subitem">
					<a href="#">Tous les jeux vidéo</a>
				</li>
				<li class="subitem">
					<a href="#">Consoles et Accessoires</a>
				</li>
				<li class="subitem">
					<a href="#">Jeux PC</a>
				</li>
			</div>
			<div class="col-xs-6">
			</div>
			
			<li>
				<img class="img_promo" style="
					bottom: -54px;
					right: -40px;
					width: 540px;
					height: 523px;
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/jeux_videos.png' ?>" alt="Jeux vidéo et Consoles">
			</li>
		</ul>
	</li>


	<li class="item">
		<a href="#">
			High-Tech et Informatique
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">High-Tech</span>
				</li>
				<li class="subitem">
					<a href="#">Téléphones portables & fixes</a>
				</li>
				<li class="subitem">
					<a href="#">Photo & Caméscopes</a>
				</li>
				<li class="subitem">
					<a href="#">TV & Home cinéma</a>
				</li>
				<li class="subitem">
					<a href="#">Audio & HiFi</a>
				</li>
				<li class="subitem">
					<a href="#">GPS & Auto</a>
				</li>
				<li class="subitem">
					<a href="#">Instruments de musique & Sono</a>
				</li>
				<li class="subitem">
					<a href="#">Objets connectés</a>
				</li>
				<li class="subitem">
					<a href="#">Tous les accessoires High-Tech</a>
				</li>
				<li class="subitem">
					<a href="#">Tout l'univers High-Tech</a>
				</li>
			</div>
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Informatique et bureau</span>
				</li>
				<li class="subitem">
					<a href="#">Ordinateurs portables & Tablettes</a>
				</li>
				<li class="subitem">
					<a href="#">Ordinateurs de bureau & Ecrans</a>
				</li>
				<li class="subitem">
					<a href="#">Stockage & Réseaux</a>
				</li>
				<li class="subitem">
					<a href="#">Composants PC</a>
				</li>
				<li class="subitem">
					<a href="#">Imprimantes & Encres</a>
				</li>
				<li class="subitem">
					<a href="#">Logiciels</a>
				</li>
				<li class="subitem">
					<a href="#">Fournitures scolaires et de bureau</a>
				</li>
				<li class="subitem">
					<a href="#">Jeux PC</a>
				</li>
				<li class="subitem">
					<a href="#">Tous les accessoires Informatique</a>
				</li>
				<li class="subitem">
					<a href="#">Tout l'univers Informatique</a>
				</li>
			</div>
			
			<li>
				<img class="img_promo" style="
					bottom: -34px;
					right: -20px;
					width: 511px;
					height: 431px;
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/high-tech.png' ?>" alt="High-Tech et Informatique">
			</li>
		</ul>
	</li>	

	<li class="item">
		<a href="#">
			Jouets, Enfants et Bébés
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Jouets, Enfants et Bébés</span>
				</li>
				<li class="subitem">
					<a href="#">Jeux et Jouets</a>
				</li>
				<li class="subitem">
					<a href="#">Bébés & Puériculture</a>
				</li>
				<li class="subitem">
					<a href="#">Vêtements et Chaussures</a>
				</li>
				<li class="subitem">
					<a href="#">Livres</a>
				</li>
				<li class="subitem">
					<a href="#">DVD</a>
				</li>
				<li class="subitem">
					<a href="#">Liste de naissance</a>
				</li>
				<li class="subitem">
					<a href="#">Amazon Famille</a>
					<h6 class="menu-caption">-20% sur les couches, des promotions</h6>
					<h6 class="menu-caption"> exclusives et la livraison gratuite</h6>
					
				</li>
			</div>
			<div class="col-xs-6">
			</div>
			<li>
				<img class="img_promo" style="
					bottom: -23px;
					right: -19px;
					width: 518px;
					height: 464px;
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/famille.png' ?>" alt="Jouets, enfants et bébés">
			</li>

		</ul>
	</li>


	<li class="item">
		<a href="#">
			Maison, Bricolage, Animalerie
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Cuisine & Maison</span>
				</li>
				<li class="subitem">
					<a href="#">Petit électroménager</a>
				</li>
				<li class="subitem">
					<a href="#">Aspirateurs et Repassage</a>
				</li>
				<li class="subitem">
					<a href="#">Gros électroménager</a>
				</li>
				<li class="subitem">
					<a href="#">Ameublement et Décoration</a>
				</li>
				<li class="subitem">
					<a href="#">Rangement et Organisation</a>
				</li>
				<li class="subitem">
					<a href="#">Arts culinaires et Arts de la Table</a>
				</li>
				<li class="subitem">
					<a href="#">Linge de maison</a>									
				</li>
				<li class="subitem">
					<a href="#">Literie</a>									
				</li>
				<li class="subitem">
					<a href="#">Luminaires et Eclairage</a>									
				</li>
			</div>
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Bricolage & Jardin</span>
				</li>
				<li class="subitem">
					<a href="#">Outillage électroportatif</a>
				</li>
				<li class="subitem">
					<a href="#">Outillage à main</a>
				</li>
				<li class="subitem">
					<a href="#">Plomberie et Sanitaires</a>
				</li>
				<li class="subitem">
					<a href="#">Chauffage et Climatisation</a>
				</li>
				<li class="subitem">
					<a href="#">Jardin</a>
				</li>
				<li class="subitem">
					<a href="#">Tous les produits Bricolage</a>
				</li>
				<hr>
				<li class="subitem title">
					<span class="subitem-title">Animalerie</span>
				</li>
				<li class="subitem">
					<a href="#">Tout pour les animaux</a>									
				</li>
			</div>
			<li>
				<img class="img_promo" style="
					bottom: -35px;
					right: -22px;
					width: 511px;
					height: 431px;
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/cuisine.png' ?>" alt="Maison">
			</li>
			

		</ul>
	</li>

	<li class="item">
		<a href="#">
			Beauté, Santé, Épicerie
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Beauté, Santé et Bien-être</span>
				</li>
				<li class="subitem">
					<a href="#">Toute la Beauté</a>
				</li>
				<li class="subitem">
					<a href="#">Beauté Prestige</a>
				</li>
				<li class="subitem">
					<a href="#">Univers Homme</a>
				</li>
				<li class="subitem">
					<a href="#">Hygiène et Santé</a>
				</li>
				<li class="subitem">
					<a href="#">Parapharmacie</a>
				</li>
				<li class="subitem">
					<a href="#">Entretien de la maison</a>
				</li>
				
				<hr>
				
				<li class="subitem title">
					<span class="subitem-title">Épicerie et Boissons</span>
				</li>
				<li class="subitem">
					<a href="#">Épicerie</a>
				</li>
				<li class="subitem">
					<a href="#">Bio, Sans gluten et Équitable</a>
				</li>
				<li class="subitem">
					<a href="#">Alimentation bébé</a>
				</li>
				<li class="subitem">
					<a href="#">Bières, Vins et Spiritueux</a>
				</li>
				<li class="subitem">
					<a href="#">Boissons sans alcool</a>
				</li>
				<li class="subitem">
					<a href="#">Économisez en vous abonnant</a>	
					<h6 class="menu-caption">Jusqu'à -15% et la livraison gratuite</h6> 
				</li>
			</div>
			<div class="col-xs-6">
			</div>
			
			<li>
				<img class="img_promo" style="
					bottom: -34px;
					right: -22px;
					width: 500px;
					height: 483px;
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/courses.png' ?>" alt="Courses">
			</li>
			

		</ul>
	</li>

	<li class="item">
		<a href="#">
			Vêtements et Chaussures
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:499px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Vêtements</span>
				</li>
				<li class="subitem">
					<a href="#">Femme</a>
				</li>
				<li class="subitem">
					<a href="#">Homme</a>
				</li>
				<li class="subitem">
					<a href="#">Fille</a>
				</li>
				<li class="subitem">
					<a href="#">Garçon</a>
				</li>
				<li class="subitem">
					<a href="#">Bébé</a>
				</li>
				
				
				<li class="subitem title">
					<span class="subitem-title">Chaussures</span>
				</li>
				<li class="subitem">
					<a href="#">Femme</a>
				</li>
				<li class="subitem">
					<a href="#">Homme</a>
				</li>
				<li class="subitem">
					<a href="#">Fille</a>
				</li>
				<li class="subitem">
					<a href="#">Garçon</a>
				</li>
				<li class="subitem">
					<a href="#">Bébé</a>
				</li>
				
				<li class="subitem title">
					<span class="subitem-title">Accessoires</span>
				</li>
				<li class="subitem">
					<a href="#">Sacs à main</a>
				</li>
				<li class="subitem">
					<a href="#">Sacs homme</a>
				</li>
				<li class="subitem">
					<a href="#">Bagages</a>
				</li>
				<li class="subitem">
					<a href="#">Lunettes de soleil</a>
				</li>
			<div class="col-xs-6">
			</div>
			
			<li>
				<img class="img_promo" style="
					top: 80px;
					right: -250px;
					width: 334px;
					height: 470px;
					z-index:-5;" 
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/vetements.png' ?>" alt="Vêtements">
			</li>

		</ul>
	</li>

	<li class="item">
		<a href="#">
			Montres et Bijoux
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Montres et Bijoux</span>
				</li>
				<li class="subitem">
					<a href="#">Montres</a>
				</li>
				<li class="subitem">
					<a href="#">Bijoux</a>
				</li>
			<div class="col-xs-6">
			</div>
			<li>
				<img class="img_promo" style="
					top: 40px;
					right: -270px;
					width: 540px;
					height: 523px;
					z-index:-5;"
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/montres.png' ?>" alt="Montres">
			</li>
		</ul>
	</li>
	<li class="item">
		<a href="#">
			Sports et Loisirs
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Sports et Loisirs</span>
				</li>
				<li class="subitem">
					<a href="#">Fitness et Musculation</a>
				</li>
				<li class="subitem">
					<a href="#">Football</a>
				</li>
				<li class="subitem">
					<a href="#">Camping et Randonnée</a>
				</li>
				<li class="subitem">
					<a href="#">Cyclisme</a>
				</li>
				<li class="subitem">
					<a href="#">Vêtements de sport</a>
				</li>
				<li class="subitem">
					<a href="#">Running</a>
				</li>
				<li class="subitem">
					<a href="#">Electronique</a>
				</li>
				<li class="subitem">
					<a href="#">Golf</a>
				</li>
				<li class="subitem">
					<a href="#">Tous les Sports et Loisirs</a>
				</li>
				
			<div class="col-xs-6">
			</div>
			<li>
				<img class="img_promo" style="
					top: 50px;
					right: -270px;
					width: 511px;
					height: 516px;
					z-index:-5;"
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/sports.png' ?>" alt="Sports et Loisirs">
			</li>
		</ul>
	</li>

	<li class="item">
		<a href="#">
			Auto et Moto
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Auto et Moto</span>
				</li>
				<li class="subitem">
					<a href="#">Pièces et accessoires Auto</a>
				</li>
				<li class="subitem">
					<a href="#">Outils et dépannage</a>
				</li>
				<li class="subitem">
					<a href="#">Pièces et accessoires Moto</a>
				</li>
				<li class="subitem">
					<a href="#">GPS & Auto</a>
				</li>
			<div class="col-xs-6">
			</div>
			<li>
				<img class="img_promo" style="
					top:65px;
					right: -300px;
					width: 540px;
					height: 523px;
					z-index:-5;"
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/autos.png' ?>" alt="Autos et motos">
			</li>
		</ul>
	</li>
	
	<li class="item">
		<a href="#">
			Commerce, Industrie et Science
			<span class="arrow-right glyphicon glyphicon-chevron-right"></span>
		</a>
		<ul class="submenu col-xs-12" style="width:518px;">
			<div class="col-xs-6">
				<li class="subitem title">
					<span class="subitem-title">Commerce, Industrie et Science</span>
				</li>
				<li class="subitem">
					<a href="#">Tous les produits Commerce, Industrie et Science</a>
				</li>
				<li class="subitem">
					<a href="#">Laboratoire</a>
				</li>
				<li class="subitem">
					<a href="#">Nettoyage</a>
				</li>
				<li class="subitem">
					<a href="#">Sécurité</a>
				</li>
			<div class="col-xs-6">
			</div>
			<li>
				<img class="img_promo" style="
					top: 40px;
					right: -278px;
					width: 519px;
					height: 518px;
					z-index:-5;"
				src="<?php echo $this->baseUrl() . '/imgs/img_promo/imprimantes.png' ?>" alt="Sciences">
			</li>
		</ul>
	</li>

	<hr>
	
	<li class="item last-item">
		<a href="#">
			Toutes les boutiques
		</a>
	</li>
</ul>