<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width" />
  <title>Amazon</title>
  
  <link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/jquery-ui.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl().'/boostrap3/css/bootstrap.css' ?>">
  <link rel="stylesheet" href="<?php echo $this->baseUrl().'/css/style.css' ?>">
</head>
<body>
	
<?php
include('include/header.phtml');
?>

  <?php echo $this->layout()->content ?>
  
<?php
include('include/footer.phtml');
?>

<script src="<?php echo $this->baseUrl().'/js/jquery.js'?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl().'/js/jquery-ui.js'?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl().'/js/jcarousel.js'?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl().'/js/jcarousel-controls.js'?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl().'/js/jcarousel-pagination.js'?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl().'/js/menu.js'?>" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl().'/boostrap3/js/bootstrap.js'?>" type="text/javascript"></script>

</body>