<footer class="col-md-offset-1 container-fluid">
	<div class="row">
		<div class="col-xs-3">
			<h3>Pour mieux nous connaître</h3>
			<ul class="list-unstyled">
				<li><a href="#">À propos</a></li>
				<li><a href="#">Carrières</a></li>
				<li><a href="#">Presse</a></li>
				<li><a href="#">Amazon et notre planète</a></li>
				<li><a href="#">Amazon Ensemble</a></li>
				<li><a href="#">Les Chroniques d'Amazon</a></li>
			</ul>
		</div>
		<div class="col-xs-3">
			<h3>Gagnez de l'argent</h3>
			<ul class="list-unstyled">
				<li><a href="#">Vendez sur Amazon</a></li>
				<li><a href="#">Devenez Partenaire</a></li>
				<li><a href="#">Expédié par Amazon</a></li>
				<li><a href="#">Faites la promotion de vos produits</a></li>
				<li><a href="#">Auto-publiez votre livre</a></li>
				<li><a href="#">Tous nos programmes</a></li>
			</ul>
		</div>
		<div class="col-xs-3">
			<h3>Moyens de paiement Amazon</h3>
			<ul class="list-unstyled">
				<li><a href="#">Cartes de paiement</a></li>
				<li><a href="#">Amazon Currency Converter</a></li>
				<li><a href="#">Chèques-cadeaux</a></li>
				<li><a href="#">Codes d'achat</a></li>
			</ul>
		</div>
		<div class="col-xs-3">
			<h3>Besoin d'aide ?</h3>
			<ul class="list-unstyled">
				<li><a href="#">Visualiser ou suivre vos commandes</a></li>
				<li><a href="#">Tarifs et options de livraison</a></li>
				<li><a href="#">Amazon Premium</a></li>
				<li><a href="#">Retours et remplacements</a></li>
				<li><a href="#">Application Amazon Mobile</a></li>
				<li><a href="#">Aide</a></li>
			</ul>
		</div>
	</div>
	<div class="row text-center">
		<img id="footer-logo" src="<?php echo $this->baseUrl() . '/imgs/logo-blanc.png' ?>">
	</div>
	<div class="row text-center" id="pays">
		<ul class="list-unstyled list-inline">
			<li><a href="#">Australie</a></li>
			<li><a href="#">Allemagne</a></li>
			<li><a href="#">Brésil</a></li>
			<li><a href="#">Canada</a></li>
			<li><a href="#">Chine</a></li>
			<li><a href="#">Espagne</a></li>
			<li><a href="#">États-Unis</a></li>
			<li><a href="#">Inde</a></li>
			<li><a href="#">Italie</a></li>
			<li><a href="#">Japon</a></li>
			<li><a href="#">Mexique</a></li>
			<li><a href="#">Pays-Bas</a></li>
			<li><a href="#">Royaume-Uni</a></li>
		</ul>
	</div>
	<div class="row amazon-derives" id="amazon-derives1">
		<div class="container">
			<div class="col-xs-2 col-xs-offset-1">
				<a href="#">AbeBooks </br><small>Livres rares & manuels</small></a>
			</div>
			<div class="col-xs-2">
				<a href="#">Amazon BuyVIP </br><small>Ventes privées partout en Europe</small></a>
			</div>
			<div class="col-xs-2">
				<a href="#">Amazon Web Services </br><small>Services de Cloud Computing Flexibles</small></a>
			</div>
			<div class="col-xs-2">
				<a href="#">Audible </br><small>Téléchargez des livres audio</small></a>
			</div>
			<div class="col-xs-2">
				<a href="#">Book Depository </br><small>Livres expédiés dans le monde entier</small></a>
			</div>
		</div>
	</div>
	<div class="row amazon-derives" id="amazon-derives2">
		<div class="container">
			<div class="col-xs-2 col-xs-offset-1">
				<a href="#">CreateSpace </br><small>Auto-publiez facilement vos livres au format papier</small></a>
			</div>
			<div class="col-xs-2">
				<a href="#">Kindle Direct Publishing</br><small>Auto-publiez facilement vos livres au format numérique</small></a>
			</div>
			<div class="col-xs-2">
				<a href="#">MYHABIT </br><small>Mode privée et designers</small></a>
			</div>
			<div class="col-xs-2">
				<a href="#">Offres Reconditionnées</br><small>Bonnes affaires</small></a>
			</div>
			<div class="col-xs-2">
				<a href="#">Shopbop </br><small>Vêtements de Marque & Mode</small></a>
			</div>
		</div>
	</div>
	<div class="row text-center" id="amazon-infos">
		<ul class="list-unstyled list-inline">
			<li><a href="#">Conditions générales de vente</a></li>
			<li><a href="#">Vos informations personnelles</a></li>
			<li><a href="#">Cookies et Publicité sur Internet</a></li>
			<li><small>© 1996-2015, Amazon.com, Inc. ou ses filiales.</small></li>
		</ul>
	</div>
</footer>